AllCops:
  TargetRubyVersion: 2.7.3

  Exclude:
  - 'core/model/ui.rb'

Style/FrozenStringLiteralComment:
  Enabled: false
  
Layout/IndentationWidth:
  Enabled: false

Metrics/MethodLength:
  Max: 20
