AllCops:
  TargetRubyVersion: 2.7.3
  NewCops: enable

  Exclude:
  - 'core/model/ui.rb'
  - vendor/bundle/**/*

Style/FrozenStringLiteralComment:
  Enabled: false
  
Layout/IndentationWidth:
  Enabled: false

Metrics/MethodLength:
  Max: 20
